### ISSUE TITLE
Change font color of only inline code

### ISSUE THREAD

**Issue by schmjop** [colineckert/obsidian-things#109]
Hi @colineckert,
thank you for your amazing theme!

I was wondering if it was possible to change the font color of `code` but keep the
```
code blocks
```
font color.

I was able to change the font color for both using [style settings](https://github.com/mgmeyers/obsidian-style-settings) -> `Inline code blocks font color (Light mode)` (even though I am using dark mode - maybe a bug?) but it changes both `code` and `code blocks`.

Thank you!

**Comment by moziar** [comment]
You could add the following CSS snippet to specify the inline code color that are in the code block:
```CSS
.markdown-rendered pre code{
    color: red;
}
```

**Comment by schmjop** [comment]
@moziar thanks for the advice. However, the inline code is still unchanged.

I added your snippet to `/vault/.obsidian/snippets/code.css` and enabled it in Settings -> Appearance -> CSS snippets. I used LF linebreaks and UTF-8.

Do you have an idea why it's not applied?

**Comment by moziar** [comment]
Maybe I didn't describe it clearly.

Use the CSS snippet here:
```CSS
/* modify the inline code color*/
body {
    --code-normal: green;
}

/* modify code block color */
.markdown-rendered pre code{
    color: red;
}
```

It will looks like this:
![image](https://user-images.githubusercontent.com/35004025/207412572-42044778-038a-41a0-9a7d-077fa23d4a66.png)

This code could only take effect on Reading View but not source mode or live mode.

**Comment by schmjop** [comment]
That has works somewhat. I put your CSS snippet into my `code.css`, but for me it looks like this:
![grafik](https://user-images.githubusercontent.com/60253217/207417656-fb01c474-0b0e-4dd3-85ba-b6489c9fbab2.png)

I want to be able to **only** change the color of the `inline code` while the code block stays the same. However, this snippet changes all of my code green unless it is a special character.
```css
body {
    --code-normal: green;
}
```

I am, however, in live mode. When I switch to reading mode, everything in the code block is red.
![grafik](https://user-images.githubusercontent.com/60253217/207419183-fafa12a1-adf7-476a-a15d-6bb53eb90573.png)


Do you think its possible to change the color of the `inline code` only, without affecting the code block colors in live mode?
Thank you!

**Comment by schmjop** [comment]
That works great! Now when I am in live mode the `inline code` has a custom color (red) and the `block code` has the default color.
```css
/* modify the inline code color*/
body {
    --code-normal: #e4374b;
}

/* avoid code block color changed in live mode */
.markdown-source-view.mod-cm6 .cm-line.HyperMD-codeblock {
    color: #BEC6CF;
}
```

Live mode:
![grafik](https://user-images.githubusercontent.com/60253217/207578280-3320a403-486a-4450-8a87-3e48d5d00fff.png)

However, now in reading mode, everything in the block quote is now red as well. Is there a way to change that back as well?

Reading mode:
![grafik](https://user-images.githubusercontent.com/60253217/207578438-6614b3ec-4fab-4806-a499-43a1f5dcff3d.png)

---

I just checked my theme version and it is the last one ([theme.css](https://github.com/colineckert/obsidian-things/blob/f8dbeb205a51f6172fd695e12da08dcb97b256cc/theme.css)). I also just copied the contents of `theme.css` into my themes folder but without change.

I also just discovered something when only using the theme without any snippets:
When I am in live mode I have syntax highlighting in the `code block`.:
![grafik](https://user-images.githubusercontent.com/60253217/207579385-c49ca001-4f5f-434c-a0fb-6ff2bd11ee56.png)

But when I am in in reading mode, there is no syntax highlighting. I've tried that with the Things theme and the default theme.
![grafik](https://user-images.githubusercontent.com/60253217/207579671-6b447dea-8205-4d13-8e75-de1b9f07a594.png)

Maybe thats why it does not work?
Is there something else I could test?
Thank you!

**Comment by moziar** [comment]
Maybe the hightlight issue is about the community plugins? Try to turn on the **Restricted mode** by Setting -> Options -> Community plugins, and see if it works.

Btw, in fact, you should use all the three snippets to make the effect you want, like this:
```CSS
/* modify the inline code color*/
body {
    --code-normal: #e4374b;
}

/* avoid code block color changed in live mode */
.markdown-source-view.mod-cm6 .cm-line.HyperMD-codeblock {
    color: #BEC6CF;
}

/* avoid code block color changed in Reading mode */
.markdown-rendered pre code{
    color: #BEC6CF;
}
```

And, yes, it's not quite elegant.
