### ISSUE TITLE
Escaped symbols (\[, \$, etc.) should be rendered as regular text

### ISSUE THREAD

**Issue by lebigot** [colineckert/obsidian-things#114]
Escaped symbols (`\[`, `\$`, etc.) are meant to be regular text.

The problem is that they currently appear in the same muted color as special characters (`[`, `$`, `*`, etc.).

They should be rendered in the same color as regular text, so as to be more legible (especially in dark mode).

Thanks!

**Comment by lebigot** [comment]
OK, here is the [solution](https://forum.obsidian.md/t/how-to-change-the-color-of-markdown-elements-1-etc/57477/4?u=lebigot) to this issue:
```css
.cm-s-obsidian span.cm-hmd-escape-char {
  color: var(--text-normal);
}
```
