### ISSUE TITLE
Special checkboxes have formatting for when a normal checkbox is checked

### ISSUE THREAD

**Issue by lbybrilee** [colineckert/obsidian-things#123]
![image](https://user-images.githubusercontent.com/126826968/222560951-df836492-25f0-49b9-8721-ca0d7690d4a9.png)

I don't know if this is supposed to be this way, but is there a way to make the text after special checkboxes look like when it's unchecked?

**Comment by kyoruni** [comment]
In the case of bookmarks, please write the following in the CSS of the theme.

```css
body:not(.tasks) li[data-task='b'].task-list-item.is-checked {
  color: var(--text-normal);
}
```

others

information … `body:not(.tasks) li[data-task='i'].task-list-item.is-checked`
star … `body:not(.tasks) li[data-task='*'].task-list-item.is-checked`
