### ISSUE TITLE
Command palette active row does not use the accent color

### ISSUE THREAD

**Issue by pdolezal** [colineckert/obsidian-things#124]
I set my favorite color as the accent color and the whole UI uses it to highlight buttons etc. Just the command palette and quick switch do not. Instead, they show the active row always in the same blue color.

I suppose the problem lies here:

```css
.theme-dark .modal-container .suggestion-item.is-selected {
  background: var(--blue);
}
```

I worked around the problem with a custom CSS patch that applies `--color-accent` instead, which I'd suggest as the fix. I assume that it is rather a mistake that here a hard-wired color is used, while all important colors can be customized.
