### ISSUE TITLE
heading 2 bottom border is missing

### ISSUE THREAD

**Issue by agung2001** [colineckert/obsidian-things#137]
## Environment 
- Obsidian Version : 1.3.5
- Things Version : 2.1.9

## Screenshot
![Screenshot 2023-06-03 at 06 23 03](https://github.com/colineckert/obsidian-things/assets/4479106/6ffe34ae-5bb2-482d-ad30-a15d584a7a0b)

## Problem
It seems that the bottom border is missing

## Solution
I notice that u use h2 when styling the heading [theme.css#LL296C1-L296C61](https://github.com/colineckert/obsidian-things/blob/main/theme.css#LL296C1-L296C61)
m not sure what happened but it seems the latest version of Obsidian doesn't use h2 for the heading it uses div instead
![Screenshot 2023-06-03 at 06 29 19](https://github.com/colineckert/obsidian-things/assets/4479106/7757d62c-0e54-4156-9232-5162b94d7b73)
maybe change [theme.css#LL296C1-L296C61](https://github.com/colineckert/obsidian-things/blob/main/theme.css#LL296C1-L296C61) to : 
```css
body .HyperMD-header.HyperMD-header-2.cm-line {
  border-bottom: 2px solid var(--background-modifier-border);
  width: 100%;
  padding-bottom: 2px;
}
```
it fixes the issue for me

I really like your theme man, thanks for sharing @colineckert 😄👍
Also how about setting up sass? 
I think it'll help with the development of this theme
