### ISSUE TITLE
Left padding to list

### ISSUE THREAD

**Issue by amitguptagwl** [colineckert/obsidian-things#139]
Currently a list with the indentation of paragraph. I want to give left  padding. I'm trying to modify your CSS style and add following. But it doesn't work.

```css
.markdown-source-view.mod-cm6.is-readable-line-width .HyperMD-list-line {
	margin-left: max(calc(50% + var(--list-edit-offset) + var(--folding-offset) - var(--line-width-adaptive)/ 2), calc(50% + var(--list-edit-offset) + var(--folding-offset) - var(--max-width)/ 2)) !important
}
```
