### ISSUE TITLE
Code block can't correctly display python variable color

### ISSUE THREAD

**Issue by Wannabeasmartguy** [colineckert/obsidian-things#166]
Hello! Things is the best theme I've ever used! However, during my usage, there's a problem(or feature?) border me a lot:

When I'm in edit mode, things correctly renders the corresponding colors of variables, entities, and functions in python.

![image](https://github.com/colineckert/obsidian-things/assets/107250451/93349029-ce19-4439-9202-aa0e1243913b)

But when in reading view, they all turn red.

![image](https://github.com/colineckert/obsidian-things/assets/107250451/ab2f7edc-8749-4494-b152-70b3ca99f5a1)

I've located the code block below, but I'm not sure how I should modify it, as I only know a little bit about css, but am not familiar with it.

```css
code[class*='language-'],
.token.selector,
.cm-tag,
.token.dom.variable,
.token.tag,
.cm-def,
.token.parameter,
.cm-property,
.cm-qualifier {
  color: var(--atom-red);
}
```

If you give me a suggestion, that could be of help!
