### ISSUE TITLE
[BUG] Integration with Banners

### ISSUE THREAD

**Issue by dlion** [colineckert/obsidian-things#18]
Hi,

I'm using the https://github.com/noatpad/obsidian-banners plugin with the obsidian-things theme.
I would like to use banners on my pages but apparently, it's not totally supported by your theme.

Here an example:

![image](https://user-images.githubusercontent.com/2125236/143499938-c270ed31-dfc8-4375-8f9e-5643ff355f9b.png)

As you can see just below the banner there is a URL which accordingly to the banner plugin's page it shouldn't be there.

![image](https://user-images.githubusercontent.com/2125236/143500044-bd2a82d7-9fb6-491e-afbf-d55f9c1a7dee.png)

Thank you

**Comment by dlion** [comment]
Hi, I've just added a snippet to solve temporarily the problem
```css
.theme-dark pre.frontmatter[class*='language-yaml'], .theme-light pre.frontmatter[class*='language-yaml'] {
        display: none;
}
```

This is the result:

![image](https://user-images.githubusercontent.com/2125236/144335312-8dace077-5676-4dc7-8bd8-ce8f033dbdf0.png)
