### ISSUE TITLE
How to change the color of certain tag pills?

### ISSUE THREAD

**Issue by kedanli** [colineckert/obsidian-things#61]
Hi,
Your theme is amazing. Thank you very much for sharing!!!

I would like to change the color of certain tag pills (eg #prio1, #prio2, #prio3 all in different colors). But I have Problems figuring out how to do it.

**Comment by colineckert** [comment]
Hi @kedanli - glad you like the theme!

So you can change the color of _all_ tag pills using the Style Settings plugin. Just install the plugin and look under "Typography" for light and dark mode tag pill customization options.

Unfortunately, the theme does not support custom colors based on tag name, and it's a bit to specific for me to build into the theme for everyone. But you can write additional custom CSS for that functionality in your own local Things theme CSS file.

Assuming you want the same color for light and dark mode, try adding this to your Things theme CSS file where tags stying is defined [here](https://github.com/colineckert/obsidian-things/blob/main/obsidian.css#L699) (and you can add more for any other tag names you want to cover):

```css
a[href='#prio1'] {
  background-color: red !important;
  color: white !important;
  font-size: var(--font-adaptive-small);
  font-weight: 500;
  font-family: var(--font-ui);
  padding: 3px 8px;
  text-align: center;
  text-decoration: none;
  border-radius: 20px;
}
```

Let me know if that does the trick!

**Comment by kedanli** [comment]
Hi Colin,

Thank you for your time. I really appreciate that.
I added that block of code to the css file at the „Tags" location. Sadly it does not change the colors at all. It stays the same.
Any ideas?

Best
Daniel

**Comment by colineckert** [comment]
Ah, my mistake, my solution was incomplete and didn't account for live preview. Try adding the below css [here](https://github.com/colineckert/obsidian-things/blob/main/obsidian.css#L776).

```css
a[href='#prio1'] {
  /* Choose colors */
  background-color: red !important;
  color: white !important;
  /* Don't change below */
  font-size: var(--font-adaptive-small);
  font-weight: 500;
  font-family: var(--font-ui);
  padding: 3px 8px;
  text-align: center;
  text-decoration: none;
  border-radius: 20px;
}
.cm-tag-prio1 {
  /* Choose colors */
  background-color: red !important;
  color: white !important;
  /* Don't change below */
  font-size: var(--font-adaptive-small);
  font-family: var(--font-ui);
  font-weight: 500;
  text-align: center;
  text-decoration: none;
  padding-top: 3px;
  padding-bottom: 3px;
  border-left: none;
  border-right: none;
  cursor: text;
}
```

The only thing you'll need to update is the tag selector (`#prio1` -> `#prio2` / `cm-tag-prio1` -> `cm-tag-prio2`) and the colors for each tag pill. 

Let me know if that works!
