### ISSUE TITLE
Font family override is not respected

### ISSUE THREAD

**Issue by TechTheAwesome** [colineckert/obsidian-things#91]
Even though this is similar an issue to #82 , I believe it might be a bug. 

The override will only work for `--font-editor-override` and not for `--font-text-override` even when it is set to a different font. (Interface font and Text font respectively in the setting)

Which means the Text font is not respected. even when Interface font is unset.

```css
body {
    --font-editor: var(--font-editor-override), var(--font-text-override), var(--font-editor-theme);
}
```
![image](https://user-images.githubusercontent.com/10691398/193763200-0eddbaa0-1cbd-4112-a1d3-388aeb5e8622.png)
UPDATE: Apparently view mode works, but editor + live-preview mode still uses the default font instead of override.
