### ISSUE TITLE
PDF Export - Invisible callouts, wrong colors, no indent lines

### ISSUE THREAD

**Issue by Thewest123** [colineckert/obsidian-things#96]
Hi! :) When exporting to PDF

- Heading 1 colors are wrong (light gray), Heading 2 horizontal bar is very dark
- Bullet point lists are missing vertical indent lines
- Callouts are invisible

![things-1-2](https://user-images.githubusercontent.com/11784537/196281588-81d476b8-651a-4c96-bd62-b60c84fa290e.png)

Hope this will help, thank you! :)

**Comment by Jaques22** [comment]
I've noticed this as well. It only happens when Obsidian is set to dark mode when you export the pdf, it all looks fine on light mode. 
Light mode on the left, dark mode on the right
![image](https://user-images.githubusercontent.com/38633150/197337896-71dd1db2-39d8-404c-94c9-9b9471b50d2a.png)
I haven't yet found what has or hasn't been changed in the theme from the file.

**Comment by Jaques22** [comment]
I've fixed the invisible callouts by adding this to the theme:
```css
@media print {
  .theme-dark {
    --highlight-mix-blend-mode: darken;
	--color-base-30: #ebedf0;
	--h1-color: var(--color-base-00);
  }
}
```
Will make sure it doesnt break anything else and create a PR. :)
